exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "setup/*",
]

target-version = "py310"
line-length = 120

[lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
extend-select = [
    # flake8-quotes
    "Q",
    # pep8-naming
    "N",
    # flake8-print
    "T20",
    # flake8-return
    "RSE",
    # hardcoded-password-string
    "S105",
    # refurb
    "FURB",
    # mccabe
    "C90",
]
ignore = [
    "B023",
    "N806",
    "PLR0913",
    "PLW0642",
    "SIM105",
]

[lint.per-file-ignores]
"{**/__init__.py, **/__manifest__.py}" = ["F401", "I001"]
"*__inint__.py" = ["I001"]
"**/__manifest__.py" = ["B018"]
"*/" = ["UP031"]

[lint.isort]
section-order = ["future", "standard-library", "third-party", "odoo", "odoo-addons", "first-party", "local-folder"]

[lint.isort.sections]
"odoo" = ["odoo"]
"odoo-addons" = ["odoo.addons"]

[lint.mccabe]
max-complexity = 16
