{
    "name": "Estate",
    "author": "Olga Krikunova",
    "version": "18.0.1.0.0",
    "license": "LGPL-3",
    "category": "Real Estate/Brokerage",
    "depends": ["base"],
    "data": [
        "security/estate_security.xml",
        "security/ir.model.access.csv",
        "views/estate_property_views.xml",
        "views/estate_property_offer.xml",
        "views/estate_property_type_view.xml",
        "views/estate_property_tag.xml",
        "views/estate_menus.xml",
        "views/base.view_users_form.xml",
        "data/property_type_data.xml",
    ],
    "demo": [
        "demo/property_type_demo.xml",
        "demo/property_offer_demo.xml",
    ],
    "installable": True,
    "application": True,
}
